#!/bin/bash
/usr/local/bin/npm install express -g
/usr/local/bin/npm install -g webpack
/usr/local/bin/npm install -g karma-cli
/usr/local/bin/npm install -g jasmine
/usr/local/bin/npm install -g forever

cd /home/ec2-user/crunchy-tunes
/usr/local/bin/npm install
/usr/local/bin/npm install --only=dev
